package org.klim405;// Generated by Selenium IDE
// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static java.lang.Thread.sleep;
import static org.junit.Assert.assertEquals;

public class SearchInputTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void searchInput() throws InterruptedException {
        driver.get("https://www.youtube.com/");
        driver.manage().window().setSize(new Dimension(1047, 775));
        sleep(1000);
        driver.findElement(By.xpath("//*[@id=\"search-icon-legacy\"]/yt-icon/yt-icon-shape/icon-shape/div")).click();
        sleep(1000);
        vars.put("pageurl_1", js.executeScript("return window.location.href;"));
        sleep(1000);
        assertEquals(vars.get("pageurl_1").toString(), "https://www.youtube.com/");
        sleep(1000);
        driver.findElement(By.name("search_query")).click();
        sleep(1000);
        driver.findElement(By.id("contents")).click();
        sleep(1000);
        driver.findElement(By.name("search_query")).sendKeys("котики");
        sleep(1000);
        driver.findElement(By.name("search_query")).sendKeys(Keys.ENTER);
        sleep(1000);
        vars.put("pageurl_2", js.executeScript("return window.location.href;"));
        sleep(1000);
        assertEquals(vars.get("pageurl_2").toString(), "https://www.youtube.com/results?search_query=%D0%BA%D0%BE%D1%82%D0%B8%D0%BA%D0%B8");
        sleep(10000);
    }
}
