package org.klim405;// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;

import static java.lang.Thread.sleep;


public class SearchInputTest {
    private WebDriver driver;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void searchInput() throws InterruptedException {
        driver.get("https://www.youtube.com/");
        driver.manage().window().setSize(new Dimension(1047, 775));
        driver.findElement(By.name("search_query")).click();
        sleep(1000);
        driver.findElement(By.name("search_query")).sendKeys("котики");
        sleep(1000);
        driver.findElement(By.name("search_query")).sendKeys(Keys.ENTER);
        sleep(10000);
    }
}
