package org.klim405;

// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static java.lang.Thread.sleep;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertThat;

public class VideoWrongUrlTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void videoWrongUrl() throws InterruptedException {
        driver.get("https://www.youtube.com/watch?v=MOEtQSjjswu");
        sleep(1000);
        assertThat(driver.findElement(By.xpath("//*[@id=\"contents\"]/ytd-background-promo-renderer/div[1]/div")).getText(), is("Это видео больше не доступно."));
        sleep(1000);
        driver.findElement(By.cssSelector(".yt-spec-button-shape-next--outline > yt-touch-feedback-shape:nth-child(2) .yt-spec-touch-feedback-shape__fill")).click();
        sleep(1000);
        vars.put("pageurl", js.executeScript("return window.location.href;"));
        sleep(1000);
        assertEquals(vars.get("pageurl").toString(), "https://www.youtube.com/");
        sleep(10000);
    }
}

