package org.klim405;
// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import static java.lang.Thread.sleep;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class VideoUrlTest {
    private WebDriver driver;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void videoUrl() throws InterruptedException {
        driver.get("https://www.youtube.com/watch?v=MOEtQSswu3s");
        sleep(1000);
        assertThat(driver.findElement(By.xpath("//*[@id=\"title\"]/h1/yt-formatted-string")).getText(), is("Самые смешные животные / Приколы с котами и собаками 2023"));
        sleep(10000);
    }
}
